[keys.normal]
"^" = "goto_line_start"
"$" = "goto_line_end"
"'" = "keep_primary_selection"

[keys.normal.","]
m = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
g = ":sh zellij run -cf -x 10% -y 10% --width 80% --height 80% -- lazygit"

[keys.normal.g]
l = "jump_view_right"
h = "jump_view_left"
j = "jump_view_down"
k = "jump_view_up"

[keys.insert]
j = { k = "normal_mode" }
