require('plugins.lspconfig')
require('plugins.null-ls')
require('plugins.luasnip')
require('plugins.nvim-cmp')
require('plugins.hop')
require('plugins.treesitter')
require('plugins.neoscroll')
require('plugins.symbols_outline')
require('plugins.nvim-lsp-installer')
require('plugins.goto-preview')
require('plugins.gitsigns')
require('plugins.nvim-tree')
require('plugins.telescope')

-- One liners - move to their own file if we ever add config
require('octo').setup()
